---
############################################################################
# Setup the Time
- name: Set the local timezone...
  timezone:
    name: "{{ this_timezone }}"
  become: true

- name: Configure NTP syncing...
  replace:
    path: "/etc/systemd/timesyncd.conf"
    after: '[Time]'
    regexp: '#'
    replace: ''

- name: Specify the primary NTP sync server...
  replace:
    path: "/etc/systemd/timesyncd.conf"
    after: '[Time]'
    regexp: '^NTP=$'
    replace: 'NTP=pool.ntp.org'

