# Author: Dustin Brothers
# Description:
#   yaml playbook to update the Clustering repo and script on my different PIs
---
- hosts: all
  tasks:
    - name: Pull latest local data collector script...
      ansible.builtin.shell:
        cmd: git pull origin main
        chdir: ~/python_dev_env/Clustering
    - name: Remove data.json file...
      ansible.builtin.file:
        path: ~/data.json
        state: absent
