---
############################################################################
# Setup some things first...
- name: Verify some needed files are present in the HOME directory...
  ansible.builtin.file:
    path: "{{ item }}"
    mode: '0740'
    state: touch
    modification_time: preserve
    access_time: preserve
  loop:
    - "{{ this_home }}/.bashrc"
    - "{{ this_home }}/.alias"

- name: Create the bin folder...
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0740'
  loop:
    - "{{ this_home }}/bin/"

- name: Register the shell set...
  shell: |
    echo $0
  register: shell_name
  ignore_errors: true
  changed_when: false
  no_log: true

############################################################################
# Dump tools to specific folders...
- name: Switch to BASH as the shell
  when: shell_name.stdout != "/bin/sh" and this_distro == "MacOSX"
  shell:
    cmd: "chsh -s /bin/bash"

- name: Fetch terminal tools and colors
  ansible.builtin.get_url:
    url: "{{ item }}"
    dest: "{{ this_home }}/bin/"
    mode: '0740'
  loop:
    - "https://raw.githubusercontent.com/rdustinb/WrenchAndGear/master/bin/ps1_coloring"
    - "https://raw.githubusercontent.com/rdustinb/WrenchAndGear/master/bin/list_all.py"
    - "https://raw.githubusercontent.com/rdustinb/WrenchAndGear/master/bin/read_temperature"

- name: Add my PS1 coloring script to the bashrc file...
  ansible.builtin.lineinfile:
    path: "{{ this_home }}/.bashrc"
    regexp: '^source ~/bin/ps1_coloring'
    line: "source ~/bin/ps1_coloring"

- name: Add my listing script to the alias file...
  ansible.builtin.lineinfile:
    path: "{{ this_home }}/.alias"
    regexp: '^alias ll='
    line: "alias ll='python3 ~/bin/list_all.py'"

- name: Add my CPU temperature reading script to the alias file...
  when: this_distro != "MacOSX"
  ansible.builtin.lineinfile:
    path: "{{ this_home }}/.alias"
    regexp: '^alias readTemp='
    line: "alias readTemp='~/bin/read_temperature'"

- name: Add the docker cleanup alias...
  ansible.builtin.lineinfile:
    path: "{{ this_home }}/.alias"
    regexp: '^alias docker-clean'
    line: "alias docker-clean='docker container prune -f ; docker image prune -f ; docker network prune -f ; docker volume prune -f'"

- name: Reset the DNS Cache command for macOS
  when: this_distro == "MacOSX"
  ansible.builtin.lineinfile:
    path: "{{ this_home }}/.alias"
    regexp: '^alias dnsCacheReset='
    line: "alias dnsCacheReset='sudo dscacheutil -flushcache; sudo killall -HUP mDNSResponder'"

- name: Recapture disk space for macOS
  when: this_distro == "MacOSX"
  ansible.builtin.lineinfile:
    path: "{{ this_home }}/.alias"
    regexp: '^alias diskSpaceClean='
    line: "alias diskSpaceClean='echo -e \"\nRunning docker system prune...\"; docker system prune -a; echo -e \"\nRunning timemachine local snapshot prune...\"; sudo tmutil deletelocalsnapshots /;'"

- name: Alias iCloud Drive as a shortcut for macOS
  when: this_distro == "MacOSX"
  ansible.builtin.lineinfile:
    path: "{{ this_home }}/.alias"
    regexp: '^alias cd_icloudDrive='
    line: "alias cd_icloudDrive='cd ~/Library/Mobile Documents/com~apple~CloudDocs/'"

- name: Prune downloaded files within iCloud Drive for macOS
  when: this_distro == "MacOSX"
  ansible.builtin.lineinfile:
    path: "{{ this_home }}/.alias"
    regexp: '^alias pruneIcloudDownloads='
    line: "alias pruneIcloudDownloads='find . -type f -exec brctl evict {} \\;'"
