# Author: Dustin Brothers
# Description:
#   Setup the Docker Environment
---
- hosts: all
  tasks:
    ############################################################################
    # Setup my Docker Environment
    - name: Fetch Docker setup script...
      get_url:
        url: https://get.docker.com
        dest: ~/docker_setup.sh
        mode: '0777'
    - name: Run Docker setup...
      shell: 
        cmd: /home/{{ ansible_ssh_user }}/docker_setup.sh
      become: true
    - name: Adding my user to the docker group...
      user:
        append: true
        groups: docker
        name: "{{ ansible_ssh_user }}"
      become: true
    - name: Fetch my docker playbook...
      get_url:
        url: https://raw.githubusercontent.com/rdustinb/WrenchAndGear/master/docker/docker-compose.yml
        dest: ~/

