# Author: Dustin Brothers
# Description:
#   yaml playbook to setup a RPi Macintosh Emulation system
---
- import: base_setup.yml
- hosts: all
  tasks:
    ############################################################################
    # Install Common Packages I use
    - name: Install needed packages...
      apt: 
        update_cache: yes
        pkg:
          - python3-psutil
          - stress
          - xserver-xorg-input-libinput
    ############################################################################
    # Enable 2.8" LCD Display
    - name: Enable LCD Boot Overlays, append to end of file
      blockinfile:
        path: /boot/config.txt
        content: |
          dtoverlay=vc4-kms-v3d
          dtoverlay=vc4-kms-dpi-2inch8
          dtoverlay=waveshare-28dpi-3b-4b   
          dtoverlay=waveshare-touch-28dpi
      become: true

    - name: Download LCD DTBO Files
      get_url:
        url: https://files.waveshare.com/upload/b/b5/28DPI-DTBO.zip
        dest: /tmp

    - name: Extract LCD DTBO Files to /boot/overlays
      unarchive:
        src: /tmp/28DPI-DTBO.zip
        dest: /boot/overlays
        remote_src: yes
      become: true

    - name: Rotate the LCD output to the correct orientation
      lineinfile:
        path: /etc/xdg/lxsession/LXDE-pi/autostart
        line: 'xrandr -o 3'
      become: true

    - name: Copy configuration file to rotate the touch interface
      copy:
        src: /usr/share/X11/xorg.conf.d/40-libinput.conf
        dest: /etc/X11/xorg.conf.d/
        remote_src: yes
      become: true

    - name: Rotate the LCD touch interface to the correct orientation
      lineinfile:
        path: /etc/X11/xorg.conf.d/40-libinput.conf
        insertafter: 'MatchIsTouchscreen'
        line: '        Option "CalibrationMatrix" "0 1 0 -1 0 1 0 0 1"'
      become: true

    ############################################################################
    # Reboot after all setup is complete...
    - name: Reboot to get group settings to take effect...
      reboot:
        msg: "Rebooting machine..."
      become: true
