# Author: Dustin Brothers
# Description:
#   yaml playbook to setup a RPi Macintosh Emulation system
---
- hosts: all
  tasks:
    - name: Normal Upgrade of packages
      apt: 
        upgrade: yes
        update_cache: yes 
      become: true
    ############################################################################
    # Install Common Packages I use
    - name: Install needed packages...
      apt: 
        update_cache: yes
        pkg:
          - git
          - vim
          - curl
          - fontforge
          - python3-pip
          - python3-psutil
          - stress
          - python3-venv
          - lshw
          - xserver-xorg-input-libinput
          - libsdl2-dev
          - htop
      become: true
    - name: Create several folders needed...
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - ~/bin/
        - ~/.fonts/
    ############################################################################
    # Install custom tools
    - name: Fetch terminal tools and colors
      get_url:
        url: "{{ item }}"
        dest: ~/bin/
      loop: 
        - https://raw.githubusercontent.com/rdustinb/WrenchAndGear/master/bin/ps1_coloring
        - https://raw.githubusercontent.com/rdustinb/WrenchAndGear/master/bin/list_all.py
    - name: Add my listing script to the bashrc...
      shell:
        cmd: echo "alias ll='python3 ~/bin/list_all.py'" >> ~/.bashrc
    - name: Add my PS1 coloring script to the bashrc...
      shell:
        cmd: echo "source ~/bin/ps1_coloring" >> ~/.bashrc
    ############################################################################
    # Setup my VIM Environment
    - name: Fetch VIM .vimrc
      get_url:
        url: https://raw.githubusercontent.com/rdustinb/WrenchAndGear/master/setup/.vimrc
        dest: ~/
    - name: Fetch VIM font
      get_url:
        url: https://github.com/powerline/fonts/raw/master/SourceCodePro/Source%20Code%20Pro%20for%20Powerline.otf
        dest: ~/
    - name: Convert VIM font...
      shell:
        cmd: fontforge -lang=ff -c 'Open($1); Generate($2);' ~/Source%20Code%20Pro%20for%20Powerline.otf ~/.fonts/Source\ Code\ Pro\ for\ Powerline.ttf
    - name: Update font cache...
      shell:
        cmd: fc-cache
    - name: Download VIM Colorschemes which also create the initial .vim folder structure...
      git:
        repo: https://github.com/flazz/vim-colorschemes.git
        dest: ~/.vim
    - name: Create several other VIM tool folders needed...
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - ~/.vim/autoload
        - ~/.vim/bundle
        - ~/.vim/plugin
        - ~/.vim/pack/airblade/start
    - name: Fetch Pathogen
      get_url:
        url: https://tpo.pe/pathogen.vim
        dest: ~/.vim/autoload/
    - name: Download VIM NerdTree...
      git:
        repo: https://github.com/preservim/nerdtree.git
        dest: ~/.vim/pack/vendor/start/nerdtree
    - name: Install VIM NerdTree...
      shell:
        cmd: vim -u NONE -c "helptags ~/.vim/pack/vendor/start/nerdtree/doc" -c q
    - name: Download VIM Git Gutter tool...
      git:
        repo: https://github.com/airblade/vim-gitgutter.git
        dest: ~/.vim/pack/airblade/start
    - name: Install VIM Git Gutter tool...
      shell:
        cmd: vim -u NONE -c "helptags vim-gitgutter/doc" -c q
    - name: Fetch VIM Visual Increment
      get_url:
        url: https://raw.githubusercontent.com/triglav/vim-visual-increment/master/plugin/visual-increment.vim
        dest: ~/.vim/plugin
    - name: Fetch VIM Visual Increment docs
      get_url:
        url: https://raw.githubusercontent.com/triglav/vim-visual-increment/master/doc/visual-increment.txt
        dest: ~/.vim/docs
    - name: Install VIM Tabular tool...
      git:
        repo: https://github.com/godlygeek/tabular.git
        dest: ~/.vim/bundle/tabular
    - name: Install VIM Airline tool...
      git:
        repo: https://github.com/vim-airline/vim-airline.git
        dest: ~/.vim/bundle/vim-airline
    - name: Install VIM Airline themes...
      git:
        repo: https://github.com/vim-airline/vim-airline-themes.git
        dest: ~/.vim/bundle/vim-airline-themes
    - name: Install VIM Indent guides...
      git:
        repo: https://github.com/preservim/vim-indent-guides.git
        dest: ~/.vim/bundle/vim-indent-guides
    - name: Install VIM Xilinx TCL syntax highlighter...
      git:
        repo: https://github.com/amal-khailtash/vim-xtcl-syntax.git
        dest: ~/.vim/bundle/vim-xtcl-syntax
    - name: Install VIM Xilinx Constraints syntax highlighter...
      git:
        repo: https://github.com/amal-khailtash/vim-xdc-syntax.git
        dest: ~/.vim/bundle/vim-xdc-syntax
    - name: Install VIM SystemVerilog syntax highlighter...
      git:
        repo: https://github.com/vhda/verilog_systemverilog.vim
        dest: ~/.vim/bundle/verilog_systemverilog
          #############################################################################
          ## Enable 2.8" LCD Display
          #- name: Enable LCD Boot Overlays, append to end of file
          #  blockinfile:
          #    path: /boot/config.txt
          #    content: |
          #      dtoverlay=vc4-kms-v3d
          #      dtoverlay=waveshare-28dpi-3b-4b   
          #      dtoverlay=waveshare-28dpi-3b
          #      dtoverlay=waveshare-28dpi-4b
          #      dtoverlay=waveshare-touch-28dpi
          #      dtoverlay=vc4-kms-dpi-2inch8
          #  become: true

          #- name: Download LCD DTBO Files
          #  get_url:
          #    url: https://files.waveshare.com/upload/b/b5/28DPI-DTBO.zip
          #    dest: /tmp

          #- name: Extract LCD DTBO Files to /boot/overlays
          #  unarchive:
          #    src: /tmp/28DPI-DTBO.zip
          #    dest: /boot/overlays
          #    remote_src: yes
          #  become: true

          #- name: Rotate the LCD output to the correct orientation
          #  lineinfile:
          #    path: /etc/xdg/lxsession/LXDE-pi/autostart
          #    line: 'xrandr -o 3'
          #  become: true

          #- name: Copy configuration file to rotate the touch interface
          #  copy:
          #    src: /usr/share/X11/xorg.conf.d/40-libinput.conf
          #    dest: /etc/X11/xorg.conf.d/
          #    remote_src: yes
          #  become: true

          #- name: Rotate the LCD touch interface to the correct orientation
          #  lineinfile:
          #    path: /etc/X11/xorg.conf.d/40-libinput.conf
          #    insertafter: 'MatchIsTouchscreen'
          #    line: '        Option "CalibrationMatrix" "0 1 0 -1 0 1 0 0 1"'
          #  become: true

          #############################################################################
          ## Reboot after all setup is complete...
          #- name: Reboot to get group settings to take effect...
          #  reboot:
          #    msg: "Rebooting machine..."
          #  become: true
