---
############################################################################
# Check for the state of things first...
- name: Register if Homebrew is already installed
  shell: |
    ls /opt/homebrew/bin/brew
  register: homebrew_exists
  ignore_errors: true
  changed_when: false
  no_log: true

############################################################################
# Setup the Homebrew package manager
- name: Install Homebrew
  when: homebrew_exists is failed
  shell:
    cmd: '/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"'

# Add lines to the bash_profile and aliases files
- name: Add Homebrew to the PATH
  ansible.builtin.lineinfile:
    path: "{{ this_home }}/.bashrc"
    regexp: '^export PATH=/opt/homebrew/sbin'
    line: "export PATH=/opt/homebrew/sbin:/opt/homebrew/bin:$PATH"

