services:
  #####################################################################
  # This container runs Homebridge so I can use 'unofficial' devices with Apple's Home app.
  homebridge:
    container_name: homebridge
    image: homebridge/homebridge:latest
    restart: always
    network_mode: host
    environment:
      TZ: 'America/Denver'
    volumes:
      - '~/volumes/homebridge:/homebridge'
    logging:
      driver: json-file
      options:
        max-size: '10mb'
        max-file: '5'
