services:
  #####################################################################
  # Prometheus Metric Monitor Exporter
  node_exporter:
    container_name: node_exporter
    image: quay.io/prometheus/node-exporter:latest
    restart: unless-stopped
    ports:
      - '9100:9100'
    command:
      - '--path.rootfs=/host'
    volumes:
      - '/:/host:ro,rslave'
