services:
  #####################################################################
  # This container spins up an instance of OctoPrint
  # It requires the ARM v7 processor or greater, meaning it will not 
  # launch on the Raspberry Pi Zero W (1st gen)
  #
  # https://hub.docker.com/r/octoprint/octoprint
  octoprint:
    container_name: octoprint  
    image: octoprint/octoprint 
    restart: always
    network_mode: host
    devices:
    # use `python -m serial.tools.miniterm` to see what the name is of the printer, this requires pyserial
      - /dev/ttyAMA0:/dev/ttyAMA0     
      - /dev/ttyUSB0:/dev/ttyUSB0     
      - /dev/video0:/dev/video0
    environment:
      - TZ=America/Denver
      - ENABLE_MJPG_STREAMER=true     
    volumes:
      - '~/volumets/octoprint:/octoprint'
