version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    network_mode: host
    environment:
      TZ: 'America/Denver'
      WEBPASSWORD: 'CHANGEME'
    volumes:
      - '~/etc-pihole:/etc/pihole'
      - '~/etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped
  homebridge:
    container_name: homebridge
    image: oznu/homebridge:latest
    restart: always
    network_mode: host
    environment:
      TZ: 'America/Denver'
    volumes:
      - '~/homebridge:/homebridge'
    logging:
      driver: json-file
      options:
        max-size: '10mb'
        max-file: '5'
