#!/bin/bash

# Rotate the X display
xrandr -o 3

# Copy the current emulation configuration into the place that Basilisk expects it
cp ~/Developer/emulation/Configs/system7.5.3.config ~/.config/BasiliskII/prefs

# Launch the emulation system
BasiliskII --keycodefile ~/Developer/emulation/Keycodes/keycodes

# When the emulation system shuts down, shut down the host system to fully integrate the two
#sudo shutdown now
