# Author: Dustin Brothers
# Description:
#   yaml playbook to update all the SW on my different PIs
---
- hosts: all
  become: true
  tasks:
    - name: Normal Upgrade of packages
      apt: 
        upgrade: yes
        update_cache: yes 
    - name: Distribution Upgrade of packages
      apt: 
        upgrade: dist
        update_cache: yes 
    - name: Autoremove packages as needed
      apt: 
        autoremove: yes
        clean: yes
        update_cache: yes 
    - name: Register if reboot is necessary
      stat:
        path: /var/run/reboot-required
      register: reboot
    - name: Perform reboot
      ansible.builtin.reboot:
        post_reboot_delay: 30
      when: >
        reboot.stat.exists
