# Author: Dustin Brothers
# Description:
#   yaml playbook to pull new IMAGES of Docker containers on every host
---
- hosts: all

  tasks:
    - name: Get the Docker container NAMES fields for running containers...
      command: docker ps --format '{{ '{{' }} .Names {{ '}}' }}'
      register: docker_names

    - name: Get the Docker container IMAGES fields for all running containers...
      command: docker ps --format '{{ '{{' }} .Image {{ '}}' }}'
      register: docker_images

    - name: Pull all new Docker images...
      command: docker pull {{ item }}
      loop: "{{ docker_images.stdout_lines }}"

    - name: Rebuild the Docker containers based on their NAMES...
      command: docker compose up --force-recreate --build -d {{ item }}
      loop: "{{ docker_names.stdout_lines }}"

    - name: Remove dangling images that are no longer used...
      command: docker system prune -f
      register: docker_pruned

    - name: Print the results of the prune command...
      ansible.builtin.debug:
        msg: "{{ docker_pruned.stdout }}"
