############################################################################
# Create folders needed
- name: Create the emulation configuration directories
  file:
    path:
      - ~/Developer/emulation/Configs
      - ~/Developer/emulation/ROMs
      - ~/Developer/emulation/Floppys
      - ~/Developer/emulation/HDDs
      - ~/Developer/emulation/Keycodes
    recurse: true
    state: directory

############################################################################
# Clone and build Basilisk II from source
- name: Clone the latest Basilisk II source
  git:
    repo: https://github.com/kanjitalk755/macemu.git
    dest: ~/macemu

- name: Autogen the Basilisk II source
  shell:
    chdir: ~/macemu/BasiliskII/src/Unix
    cmd: NO_CONFIGURE=1 ./autogen.sh

- name: Configure the Basilisk II source
  shell:
    chdir: ~/macemu/BasiliskII/src/Unix
    cmd: ./configure --enable-sdl-video=yes --enable-sdl-audio=yes --with-bincue

- name: Make the Basilisk II source
  shell:
    chdir: ~/macemu/BasiliskII/src/Unix
    cmd: make

- name: Strip Basilisk II
  shell:
    chdir: ~/macemu/BasiliskII/src/Unix
    cmd: strip BasiliskII

- name: Install Basilisk II
  shell:
    chdir: ~/macemu/BasiliskII/src/Unix
    cmd: make install
  become: true

############################################################################
# Fetch the Emulation Files needed
- name: Fetch the ROM file
    chdir: ~/Developer/emulation/ROMs
    cmd: wget https://github.com/rdustinb/WrenchAndGear/raw/master/emulation/ROMs/ColorClassic-1MB.rom

- name: Fetch the Boot Floppy
    chdir: ~/Developer/emulation/Floppys
    cmd: wget https://github.com/rdustinb/WrenchAndGear/raw/master/emulation/Basilisk/Floppys/System7_Boot.dsk

- name: Fetch the System 7.5.3 Install Floppys
    chdir: ~/Developer/emulation/Floppys
    cmd: wget https://github.com/rdustinb/WrenchAndGear/raw/master/emulation/Basilisk/Floppys/System7.5.3_Install.dsk

- name: Fetch the System 7.5.5 Update Floppys
    chdir: ~/Developer/emulation/Floppys
    cmd:
      - wget https://github.com/rdustinb/WrenchAndGear/raw/master/emulation/Basilisk/Floppys/System7.5.5_Update_1.dsk
      - wget https://github.com/rdustinb/WrenchAndGear/raw/master/emulation/Basilisk/Floppys/System7.5.5_Update_2.dsk
      - wget https://github.com/rdustinb/WrenchAndGear/raw/master/emulation/Basilisk/Floppys/System7.5.5_Update_3.dsk

- name: Write configuration to a file
  blockinfile:
    path: ~/Developer/emulation/Configs/system.config
    block: |
      rom /home/{{ ansible_user }}/Developer/emulation/ROMs/ColorClassic-1MB.rom
      disk /home/{{ ansible_user }}/Developer/emulation/HDDs/System7_Boot.dsk
      disk /home/{{ ansible_user }}/Developer/emulation/HDDs/System7.5.3_Install.dsk
      disk /home/{{ ansible_user }}/Developer/emulation/HDDs/System7.5.5_Update_1.dsk
      disk /home/{{ ansible_user }}/Developer/emulation/HDDs/System7.5.5_Update_2.dsk
      disk /home/{{ ansible_user }}/Developer/emulation/HDDs/System7.5.5_Update_3.dsk
      disk /home/{{ ansible_user }}/Developer/emulation/HDDs/HDD.dsk
      extfs /home/{{ ansible_user }}/Shared
      screen win/640/480
      seriala /dev/cu.BLTH
      serialb /dev/null
      udptunnel false
      udpport 6066
      bootdrive 0
      bootdriver 0
      ramsize 67108864
      frameskip 0
      modelid 5
      cpu 1
      fpu false
      nocdrom true
      nosound true
      noclipconversion false
      nogui false
      jit false
      jitfpu true
      jitdebug false
      jitcachesize 8192
      jitlazyflush true
      jitinline true
      keyboardtype 5
      keycodes true
      keycodefile 
      mousewheelmode 0
      mousewheellines 0
      dsp 
      mixer 
      ignoresegv true
      idlewait false
      displaycolordepth 0
      hotkey 0
      scale_nearest false
      scale_integer false
      yearofs 0
      dayofs 0
      mag_rate 0
      swap_opt_cmd false
      sound_buffer 0
      name_encoding 0
      delay 0
      init_grab false

- name: Add xsession file
    chdir: ~/
    cmd: wget https://raw.githubusercontent.com/rdustinb/WrenchAndGear/master/emulation/MacintoshPi%20Build/.xsession

- name: Get keycodes mappings file
    chdir: ~/Developer/emulation/Keycodes
    cmd: wget https://raw.githubusercontent.com/rdustinb/WrenchAndGear/master/emulation/MacintoshPi%20Build/keycodes
