############################################################################
# Enable 2.8" LCD Display
- name: Enable LCD Boot Overlays, append to end of file
  become: true
  blockinfile:
    path: /boot/firmware/config.txt
    content: |
      dtoverlay=vc4-kms-v3d
      dtoverlay=waveshare-28dpi-3b-4b   
      dtoverlay=waveshare-28dpi-3b
      dtoverlay=waveshare-28dpi-4b
      dtoverlay=waveshare-touch-28dpi
      dtoverlay=vc4-kms-dpi-2inch8

- name: Download LCD DTBO Files
  get_url:
    url: https://files.waveshare.com/upload/b/b5/28DPI-DTBO.zip
    dest: /tmp

- name: Extract LCD DTBO Files
  become: true
  unarchive:
    src: /tmp/28DPI-DTBO.zip
    dest: /tmp
    remote_src: yes

- name: Copy files to overlay folder
  become: true
  copy:
    src: "{{ item }}"
    dest: /boot/overlays/
    remote_src: yes
  loop:
    - /tmp/28DPI-DTBO/vc4-kms-DPI-28inch.dtbo
    - /tmp/28DPI-DTBO/waveshare-28dpi.dtbo
    - /tmp/28DPI-DTBO/waveshare-28dpi-3b.dtbo
    - /tmp/28DPI-DTBO/waveshare-28dpi-4b.dtbo
    - /tmp/28DPI-DTBO/waveshare-28dpi-3b-4b.dtbo
    - /tmp/28DPI-DTBO/waveshare-touch-28dpi.dtbo

- name: Rotate the display
  become: true
  blockinfile:
    path: /etc/xdg/lxsession/LXDE-pi/autostart
    content: |
      xrandr -o 3

- name: Append to the end of the cmdline arguments...
  become: true
  lineinfile: 
    dest: /boot/firmware/cmdline.txt 
    line: " fbcon=rotate:1"

############################################################################
# Enable 2.8" LCD Touch
- name: Copy configuration file to rotate the touch interface
  copy:
    src: /usr/share/X11/xorg.conf.d/40-libinput.conf
    dest: /etc/X11/xorg.conf.d/
    remote_src: yes
  become: true

- name: Rotate the LCD touch interface to the correct orientation
  lineinfile:
    path: /etc/X11/xorg.conf.d/40-libinput.conf
    insertafter: 'MatchIsTouchscreen'
    line: '        Option "CalibrationMatrix" "0 1 0 -1 0 1 0 0 1"'
  become: true

############################################################################
# Reboot to get the display settings to take effect
- name: Rebooting...
  become: true
  reboot:
    msg: "Rebooting machine..."

