# Author: Dustin Brothers
# Description:
#   yaml playbook to update the Clustering repo and script on my different PIs
---
- hosts: all
  tasks:
    - name: Run the stress test on one core for 1 minute...
      command: /home/pi/python_dev_env/bin/stressberry-run -i 5 -d 60 -c 1 --cooldown 5 ansible_stress.dat
    - name: Run the stress test on two cores for 1 minute...
      command: /home/pi/python_dev_env/bin/stressberry-run -i 5 -d 60 -c 2 --cooldown 5 ansible_stress.dat
    - name: Run the stress test on three cores for 1 minute...
      command: /home/pi/python_dev_env/bin/stressberry-run -i 5 -d 60 -c 3 --cooldown 5 ansible_stress.dat
    - name: Run the stress test on four cores for 1 minute...
      command: /home/pi/python_dev_env/bin/stressberry-run -i 5 -d 60 -c 4 --cooldown 5 ansible_stress.dat

    - name: Run the stress test on one core for 2 minute...
      command: /home/pi/python_dev_env/bin/stressberry-run -i 5 -d 120 -c 1 --cooldown 5 ansible_stress.dat
    - name: Run the stress test on two cores for 2 minute...
      command: /home/pi/python_dev_env/bin/stressberry-run -i 5 -d 120 -c 2 --cooldown 5 ansible_stress.dat
    - name: Run the stress test on three cores for 2 minute...
      command: /home/pi/python_dev_env/bin/stressberry-run -i 5 -d 120 -c 3 --cooldown 5 ansible_stress.dat
    - name: Run the stress test on four cores for 2 minute...
      command: /home/pi/python_dev_env/bin/stressberry-run -i 5 -d 120 -c 4 --cooldown 5 ansible_stress.dat

    - name: Run the stress test on one core for 3 minute...
      command: /home/pi/python_dev_env/bin/stressberry-run -i 5 -d 180 -c 1 --cooldown 5 ansible_stress.dat
    - name: Run the stress test on two cores for 3 minute...
      command: /home/pi/python_dev_env/bin/stressberry-run -i 5 -d 180 -c 2 --cooldown 5 ansible_stress.dat
    - name: Run the stress test on three cores for 3 minute...
      command: /home/pi/python_dev_env/bin/stressberry-run -i 5 -d 180 -c 3 --cooldown 5 ansible_stress.dat
    - name: Run the stress test on four cores for 3 minute...
      command: /home/pi/python_dev_env/bin/stressberry-run -i 5 -d 180 -c 4 --cooldown 5 ansible_stress.dat
