# Author: Dustin Brothers
# Description:
#   yaml playbook to shutdown all nodes.
---
- hosts: all
  become: true
  tasks:
    - name: Shutdown all machines
      community.general.shutdown: 
        delay: 0
        msg: "Shutting down server from Ansible..."
