# Author: Dustin Brothers
# Description:
#   yaml playbook to setup a RPi Macintosh Emulation system
---
- hosts: all
  tasks:
    #- include_tasks: ../functions/waveshare2p8inDPI_setup.yml
    #- include_tasks: ../base/lowmem_setup.yml
    # NOTE: be sure to load the Waveshare DTOverlays and modify config.txt and
    # cmdline.txt *before* booting the fresh SD card image for the first time.
    # Loading the overlays and modifying the config after first boot does not
    # seem to work properly.
    - include_tasks: ../base/base_setup.yml
    - include_tasks: ../functions/basiliskii_setup.yml
    ############################################################################
    # Setup CLI Mode (don't load the desktop)
    - name: Set CLI mode with auto-login
      shell:
        cmd: systemctl set-default multi-user.target
      become: true

    ############################################################################
    # Reboot after all setup is complete...
    - name: Reboot to get group settings to take effect...
      reboot:
        msg: "Rebooting machine..."
      become: true
