# Author: Dustin Brothers
# Description:
#   yaml playbook to setup a RPi Macintosh Emulation system
---
- hosts: all
  tasks:
    - include_tasks: ../base/base_setup.yml
    - include_tasks: ../functions/waveshare2p8inDPI_setup.yml
    - include_tasks: ../functions/basiliskii_setup.yml
    ############################################################################
    # Install Common Packages I use
    - name: Install needed packages...
      apt: 
        update_cache: yes
        pkg:
          - python3-psutil
          - stress
          - xserver-xorg-input-libinput
      become: true

    ############################################################################
    # Setup CLI Mode (don't load the desktop)
    - name: Set CLI mode with auto-login
      shell:
        cmd: systemctl set-default multi-user.target
      become: true

    ############################################################################
    # Reboot after all setup is complete...
    - name: Reboot to get group settings to take effect...
      reboot:
        msg: "Rebooting machine..."
      become: true
