- hosts: all
  gather_facts: false
  tasks:
    - name: Get CPU Info of the device
      shell: cat /proc/cpuinfo | grep -i model | tail -n1 | awk 'BEGIN { FS=":" } { print $2 }' | xargs
      register: thisCpu
    - name: Get memory usage of the device
      shell: free -ht | tail -n1 | awk '{print $2}'
      register: thisFree
    - name: Get uptime of the device
      command: uptime -p
      register: thisUptime
    - name: Get Kernel version of the OS
      shell: uname -r
      register: thisKernel
    - name: Print results!
      debug: 
        msg:
          - "{{ thisCpu.stdout    }}"
          - "{{ thisFree.stdout   }}"
          - "{{ thisUptime.stdout }}"
          - "{{ thisKernel.stdout }}"
