---
############################################################################
# Install Common Packages
- name: Install base packages
  become: true
  ansible.builtin.package:
    update_cache: true
    cache_valid_time: 3600
    pkg:
      - net-tools
      - btop
      - git
      - neovim
      - vim
      - curl
      - fontforge
      - libsdl2-dev
      - python3-pip
      - python3-venv
      - stress
      - lshw
      - systemd-timesyncd
      - ufw
      - neofetch
